name: collect-to
on:
  schedule:
    - cron:  '*/30 * * * *'
  workflow_dispatch:
  
jobs:
  collect-to:
    runs-on: ubuntu-latest
    environment: collect-to
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Insatll package
        run: yarn install
      - name: Build
        run: yarn build
      - name: Action
        run: |
          node ./dist/index.js
    env:
      CW_KEY: ${{ secrets.CW_KEY }}
      CW_OUT_ROOM_ID: ${{ secrets.CW_OUT_ROOM_ID }}
      CW_EXCLUSION_ROOMS: ${{ secrets.CW_EXCLUSION_ROOMS }}
      CW_TARGET_ACCOUNT_ID: ${{ secrets.CW_TARGET_ACCOUNT_ID }}
